// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPOXt57ELEoFh_DtKzmOXgZHNUTggNBGE',
    appId: '1:464686031456:web:d6ed81dae25d2c6c999905',
    messagingSenderId: '464686031456',
    projectId: 'iiitnr-8209c',
    authDomain: 'iiitnr-8209c.firebaseapp.com',
    storageBucket: 'iiitnr-8209c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf6q1ucIq7-FQGB60GyqxE2zpH87zJiJs',
    appId: '1:464686031456:android:5b863edeecfead70999905',
    messagingSenderId: '464686031456',
    projectId: 'iiitnr-8209c',
    storageBucket: 'iiitnr-8209c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_J-sl-T5pCPSUBKOEO_ot5cBnyj3cfjA',
    appId: '1:464686031456:ios:9d4d7c62b284a0a0999905',
    messagingSenderId: '464686031456',
    projectId: 'iiitnr-8209c',
    storageBucket: 'iiitnr-8209c.firebasestorage.app',
    iosBundleId: 'com.example.iiitNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_J-sl-T5pCPSUBKOEO_ot5cBnyj3cfjA',
    appId: '1:464686031456:ios:9d4d7c62b284a0a0999905',
    messagingSenderId: '464686031456',
    projectId: 'iiitnr-8209c',
    storageBucket: 'iiitnr-8209c.firebasestorage.app',
    iosBundleId: 'com.example.iiitNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPOXt57ELEoFh_DtKzmOXgZHNUTggNBGE',
    appId: '1:464686031456:web:0f75e0f6d2685a88999905',
    messagingSenderId: '464686031456',
    projectId: 'iiitnr-8209c',
    authDomain: 'iiitnr-8209c.firebaseapp.com',
    storageBucket: 'iiitnr-8209c.firebasestorage.app',
  );
}
